### ISSUE TITLE
Vulnerability scanner

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/blockwishlist#9]
Prestashop module security vulnerability scanner detects a vulnerability in module version 2.1.0.
But this security vulnerability applies to a module with prestashop 1.7: [https://security.friendsofpresta.org/modules/2022/06/24/blockwishlist](https://security.friendsofpresta.org/modules/2022/06/24/blockwishlist)
Maybe a good solution would be to increase the version of module in thirtybees so that there is no false alarm?

**Comment by getdatakick** [comment]
False positives is a bug in testing software, and not a problem of tested subject.

It is very easily avoidable, for example by checking module author together with the name and version.  (I know at least about 4 different modules named `paypal`)

Please file an issue in the tool instead.
